name: Commit solution

on:
 workflow_dispatch:
  inputs:
   solution-name:
    required: true
   commit-message:
    required: true
    
jobs:

 export-commit-solution:
  runs-on: ubuntu-latest
  
  steps:
   - uses: actions/checkout@v3
   - uses: microsoft/powerplatform-actions/export-solution@v0
     with:
      environment-url: ${{ secrets.ENV_JBTEST }}
      app-id: ${{ secrets.CLIENT_ID }}
      client-secret: ${{ secrets.CLIENT_SECRET }}
      tenant-id: ${{ secrets.TENANT_ID }}
      solution-name: ${{ github.event.inputs.solution-name }}
      solution-output-file: ${{ github.event.inputs.solution-name }}.zip
   - uses: microsoft/powerplatform-actions/export-solution@v0
     with:
      environment-url: ${{ secrets.ENV_JBTEST }}
      app-id: ${{ secrets.CLIENT_ID }}
      client-secret: ${{ secrets.CLIENT_SECRET }}
      tenant-id: ${{ secrets.TENANT_ID }}
      solution-name: ${{ github.event.inputs.solution-name }}
      solution-output-file: ${{ github.event.inputs.solution-name }}_managed.zip
      managed: true
   - name: Clear existing folder
     run: |
       rm -rf solutions/${{ github.event.inputs.solution-name }}/src
     shell: bash
   - uses: microsoft/powerplatform-actions/unpack-solution@v0
     with:
      solution-file: ${{ github.event.inputs.solution-name }}.zip
      solution-folder: solutions/${{ github.event.inputs.solution-name }}/src
      solution-type: Both
   - uses: EndBug/add-and-commit@v8
     with:
      message: ${{ github.event.inputs.commit-message }}
      
      
       

   
  
  
